
build:
  version: "1.0"

products:
  message: "Welcome to CartWorks products related production APIs "
  contactDetails:
    name: "Yaron Olivcovitz - Product Owner"
    email: "yaron.olivcovitz@cartworks.com"
  onCallSupport:
    - (058) 565-9890
    - (054) 441-3232
