
build:
  version: "2.0"

products:
  message: "Welcome to Cartworks products related QA APIs "
  contactDetails:
    name: "Maayan Olivcovitz - QA Lead"
    email: "Maayan.olivcovitz@cartworks.com"
  onCallSupport:
    - (054) 655-5142
    - (052) 665-8784